### ISSUE TITLE
WiderFace accuracy about 62%

### ISSUE THREAD

**Issue by borisgribkov** [lippman1125/faceboxes_lqy#1]
Dear lippman1125, thanks for the code provided, we found it very useful. I would like to compare accuracy values if possible. Using your proto files and Wider Face dataset I have trained the model and finally reached about 62% of accuracy (VOC metric), at the same time this model has shown about 90% for FDDB with 1024 input. 
Did you get approximately the same values? 
I guess, that yes, because I used your 120K model for testing and obtained approx. the same numbers as mentioned above. Looking forward for your reply, thanks!

**Comment by lippman1125** [comment]
@borisgribkov 
WiderFace has so many small faces. It's difficult for faceboxes to detect them. so I covered the small faces which size below 20x20 when I trained the model.
FDDB has bigger size faces. so the accuracy is better.  fp = 100,  precision >= 88%.
If you want to find tiny faces. I think you can try more complicated model. such as SSH.

**Comment by borisgribkov** [comment]
@lippman1125 Thanks a lot, sorry, missed your answer (

**Comment by lippman1125** [comment]
@borisgribkov I reproduce S3FD， you can use this face detection. It can find small faces.
https://github.com/lippman1125/caffe_s3fd/tree/ssd

**Comment by borisgribkov** [comment]
Thanks a lot! will have a look at it, at the moment I found initial FaceBoxes very useful, because it's very fast. Detection of very small faces is not so important at the moment, but thank you anyway! )
